###
# Run a docker-based test of tests.
#
# See https://github.com/Unidata/docker-nctests
# How    https://github.com/WardF/netcdf-test-action

on: [pull_request,workflow_dispatch]

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions: {} 

jobs:  
  netcdf-tests:
    name: Docker-Based NetCDF-C, Fortran Regression Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c-branch: [ 'v4.9.0', 'v4.9.2' ]
        fortran-branch: [ 'v4.6.1' ]
        c-compiler: [ 'gcc', 'clang', 'mpicc' ]
        buildsystem: [ 'cmake', 'autotools' ]
    steps:
      - uses: actions/checkout@v4
      - name: Pull and Run netCDF Regression Tests
        uses: WardF/netcdf-test-action@v1
        with:
          run-c: 'TRUE'
          c-compiler: '${{ matrix.c-compiler }}'
          c-branch: '${{ matrix.c-branch }}'
          run-fortran: 'TRUE'
          fortran-branch: '${{ matrix.fortran-branch }}'
          build-system: '${{ matrix.buildsystem }}'
